In [10]:
%pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [11]:
import numpy as np

### O que é um vetor?

- Um vetor é uma sequência ordenada de números. Ele pode representar muitas coisas:
    - Uma posição no espaço (ex: [x, y])
    - características de um dado (ex: [altura, peso, idade])
    - Probabilidades (ex: [0.1, 0.4, 0.6])
- Em álgebra linear, vetores são elementos de uma dimensão.
- No NumPy, vetores são arrays de 1 dimensão.

In [12]:
vetor = np.array([1, 2, 3])

print(f"Vetor: {vetor}")
print(f"Tipo: {type(vetor)}")
print(f"Dimensão (ndim): {vetor.ndim}")
print(f"Tamanho (len): {len(vetor)}")
print(f"Shape: {vetor.shape}")

Vetor: [1 2 3]
Tipo: <class 'numpy.ndarray'>
Dimensão (ndim): 1
Tamanho (len): 3
Shape: (3,)


### Produto escalar com np.dot

O produto escalar (ou *dot product*) entre dois vetores de mesma dimensão resulta em um **escalar**.

#### Definição matemática

Dado dois vetores:

- a = [a₁, a₂, ..., aₙ]  
- b = [b₁, b₂, ..., bₙ]

O produto escalar é calculado como:

a · b = a₁·b₁ + a₂·b₂ + ... + aₙ·bₙ

Ou seja, é a soma das multiplicações dos elementos correspondentes.

#### Exemplo

Sejam:

- a = [1, 2, 3]  
- b = [4, 5, 6]

Então:

a · b = (1×4) + (2×5) + (3×6)  
a · b = 4 + 10 + 18 = **32**

#### Como o NumPy calcula isso

```python
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(np.dot(a, b))  # Saída: 32

In [13]:
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])

soma = v1 + v2
multiplicacao = v1 * v2
escalar = np.dot(v1, v2)

print(f"Soma: {soma}")
print(f"Multiplicação: {multiplicacao}")
print(f"Escalar: {escalar}")

Soma: [5 7 9]
Multiplicação: [ 4 10 18]
Escalar: 32


### O que é uma matriz

Uma **matriz** é uma tabela de números organizada em **linhas** e **colunas**.

Ela pode ser usada para representar dados, sistemas de equações, transformações lineares, imagens, entre outros.

#### Exemplo de matriz 2x3:

[
  [1, 2, 3],  
  [4, 5, 6]
]

Essa matriz tem:

- 2 linhas  
- 3 colunas  
- Forma (shape) = (2, 3)  
- Dimensão (ndim) = 2

#### Representação no NumPy:

```python
import numpy as np

A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
````

Cada elemento pode ser acessado por sua posição `[linha][coluna]`:

```python
A[0][1]  # retorna 2 (primeira linha, segunda coluna)
```

In [14]:
matriz = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print(f"Vetor: {matriz}")
print(f"Tipo: {type(matriz)}")
print(f"Dimensão (ndim): {matriz.ndim}")
print(f"Tamanho (len): {len(matriz)}")
print(f"Shape: {matriz.shape}")

Vetor: [[1 2 3]
 [4 5 6]]
Tipo: <class 'numpy.ndarray'>
Dimensão (ndim): 2
Tamanho (len): 2
Shape: (2, 3)


In [15]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

print(f"Soma:\n{A + B}\n")

print(f"Subtração:\n{A - B}\n")

print(f"Multiplicação elemento a elemento:\n{A * B}\n")

print(f"Multiplicação matricial (np.dot):\n{np.dot(A, B)}\n")

print(f"Multiplicação matricial (com @):\n{A @ B}")

Soma:
[[ 6  8]
 [10 12]]

Subtração:
[[-4 -4]
 [-4 -4]]

Multiplicação elemento a elemento:
[[ 5 12]
 [21 32]]

Multiplicação matricial (np.dot):
[[19 22]
 [43 50]]

Multiplicação matricial (com @):
[[19 22]
 [43 50]]


### Normalização de um vetor usando escalar

**Normalizar um vetor** significa transformá-lo para que tenha **norma 1**, ou seja, um comprimento (magnitude) igual a 1.

Isso é feito dividindo o vetor pela sua própria **norma**, que é um **escalar**.

#### Passos:

1. Calcular a norma (magnitude) do vetor.
2. Dividir cada elemento do vetor por essa norma.

#### Exemplo:

Dado o vetor:

v = [3, 4]

A norma é:

||v|| = sqrt(3² + 4²) = sqrt(9 + 16) = sqrt(25) = 5

Agora normalizamos:

v_normalizado = [3/5, 4/5] = [0.6, 0.8]

#### Em NumPy:

```python
import numpy as np

v = np.array([3, 4])
norma = np.linalg.norm(v)
v_normalizado = v / norma
````

#### Resultado:

* Norma original: 5.0
* Vetor normalizado: \[0.6, 0.8]
* Norma do vetor normalizado: 1.0


In [16]:
v = np.array([3, 4])

norma = np.linalg.norm(v)

v_normalizado = v / norma

print(f"Vetor original: {v}")
print(f"Norma (escalar): {norma}")
print(f"Vetor normalizado: {v_normalizado}")

print(np.linalg.norm(v_normalizado))

Vetor original: [3 4]
Norma (escalar): 5.0
Vetor normalizado: [0.6 0.8]
1.0
